# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Bejoy's Blog"
description: > # this means to ignore newlines until "email:"
  Lets Talk About "?"

email: bejoynj4@gmail.com
comments: true
disqus_shortname: bejoynj
#blog logo
logo: "/assets/images/bejoylogo.jpg"
# blog cover
cover: "/assets/images/banner-1.png"

name: 'Bejoy N.J'
author: 'Bejoy N.J'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://blog.bejoynj.com/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/Bejoynj
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/Bejoynj
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
